/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Fashion Inspiration template with simplified data for Storybook preview.
 * Based on the template from packages/templates/src/raw/fashion-inspiration/template.json
 */

const fashionInspirationTemplate = {
  pages: [
    {
      elements: [
        {
          opacity: 100,
          flip: { vertical: false, horizontal: false },
          rotationAngle: 0,
          lockAspectRatio: true,
          x: 1,
          y: 1,
          width: 1,
          height: 1,
          mask: { type: 'rectangle' },
          isBackground: true,
          isDefaultBackground: true,
          id: 'ac0ad0ca-5d24-40c4-90bd-e20385e6584e',
          type: 'shape',
        },
        {
          opacity: 100,
          flip: { vertical: false, horizontal: false },
          rotationAngle: 0,
          lockAspectRatio: true,
          backgroundTextMode: 'NONE',
          font: {
            family: 'Crimson Pro',
            fallbacks: ['serif'],
            weights: [200, 300, 400, 500, 600, 700, 800, 900],
            styles: ['regular', 'italic'],
            variants: [
              [0, 200],
              [0, 300],
              [0, 400],
              [0, 500],
              [0, 600],
              [0, 700],
              [0, 800],
              [0, 900],
              [1, 200],
              [1, 300],
              [1, 400],
              [1, 500],
              [1, 600],
              [1, 700],
              [1, 800],
              [1, 900],
            ],
            service: 'fonts.google.com',
            metrics: {
              upm: 1024,
              asc: 918,
              des: -220,
              tAsc: 918,
              tDes: -220,
              tLGap: 0,
              wAsc: 1006,
              wDes: 295,
              xH: 430,
              capH: 587,
              yMin: -286,
              yMax: 984,
              hAsc: 918,
              hDes: -220,
              lGap: 0,
            },
          },
          fontSize: 64,
          backgroundColor: { color: { r: 196, g: 196, b: 196 } },
          lineHeight: 1,
          textAlign: 'left',
          padding: { locked: true, hasHiddenPadding: false },
          content: '<span style="font-weight: 200; font-style: italic; color: rgba(177,140,84,0.12)">Inside look</span>',
          borderRadius: {
            locked: true,
            topLeft: 0,
            topRight: 0,
            bottomRight: 0,
            bottomLeft: 0,
          },
          width: 317,
          height: 71,
          id: '3cccfd70-c5ed-4e0a-84f8-8356b205e519',
          x: -25,
          y: 54,
          type: 'text',
          groupId: 'c535c1c2-117b-4047-8efe-e9ea57a69324',
        },
        {
          opacity: 100,
          flip: { vertical: false, horizontal: false },
          rotationAngle: -4,
          lockAspectRatio: false,
          backgroundColor: { color: { r: 193, g: 99, b: 81 } },
          x: 70,
          y: 102,
          width: 382,
          height: 254,
          mask: { type: 'rectangle' },
          id: 'be6b55fc-a396-4cfb-8e1b-4e5eb8c963cd',
          type: 'shape',
          groupId: '581825a0-be14-4515-b819-4bfacec3bf38',
        },
        {
          opacity: 100,
          flip: { vertical: false, horizontal: false },
          rotationAngle: 0,
          lockAspectRatio: false,
          scale: 110,
          focalX: 47.86749479899753,
          focalY: 65.91779387283562,
          resource: {
            type: 'image',
            mimeType: 'image/jpeg',
            creationDate: '2021-07-21T07:42:37',
            src: 'https://example.com/images/fashion-inspiration/page1_img1.jpg',
            width: 810,
            height: 1080,
            id: 0,
            alt: 'Folded clothes above hanged clothes',
            sizes: [],
            isPlaceholder: false,
            isOptimized: false,
            isMuted: false,
            baseColor: '#413a33',
            isExternal: true,
          },
          backgroundColor: { color: { r: 196, g: 196, b: 196 } },
          x: 90,
          y: 45,
          width: 322,
          height: 293,
          mask: { type: 'rectangle' },
          id: 'e6faaf99-9591-482a-90f6-c89ee6f7850b',
          type: 'image',
          groupId: '581825a0-be14-4515-b819-4bfacec3bf38',
        },
        {
          opacity: 100,
          flip: { vertical: false, horizontal: false },
          rotationAngle: 0,
          lockAspectRatio: true,
          backgroundTextMode: 'NONE',
          font: {
            family: 'Crimson Pro',
            fallbacks: ['serif'],
            weights: [200, 300, 400, 500, 600, 700, 800, 900],
            styles: ['regular', 'italic'],
            variants: [
              [0, 200],
              [0, 300],
              [0, 400],
              [0, 500],
              [0, 600],
              [0, 700],
              [0, 800],
              [0, 900],
              [1, 200],
              [1, 300],
              [1, 400],
              [1, 500],
              [1, 600],
              [1, 700],
              [1, 800],
              [1, 900],
            ],
            service: 'fonts.google.com',
            metrics: {
              upm: 1024,
              asc: 918,
              des: -220,
              tAsc: 918,
              tDes: -220,
              tLGap: 0,
              wAsc: 1006,
              wDes: 295,
              xH: 430,
              capH: 587,
              yMin: -286,
              yMax: 984,
              hAsc: 918,
              hDes: -220,
              lGap: 0,
            },
          },
          fontSize: 51,
          backgroundColor: { color: { r: 196, g: 196, b: 196 } },
          lineHeight: 1,
          textAlign: 'left',
          padding: { locked: true, hasHiddenPadding: false },
          content: '<span style="font-weight: 200">Inside</span>\n<span style="font-weight: 200">Jean Legere\'s</span>\n<span style="font-weight: 200">Closet</span>',
          borderRadius: {
            locked: true,
            topLeft: 0,
            topRight: 0,
            bottomRight: 0,
            bottomLeft: 0,
          },
          x: 47,
          y: 429,
          width: 317,
          height: 159,
          id: 'fdd58d7f-a517-4b39-b1d2-293d57ada467',
          type: 'text',
          tagName: 'h1',
        },
      ],
      animations: [],
      backgroundColor: { color: { r: 242, g: 242, b: 242 } },
      type: 'page',
      id: '12b85089-b491-41fa-8762-0286f2d49f05',
      pageTemplateType: 'cover',
      groups: {
        'c535c1c2-117b-4047-8efe-e9ea57a69324': {
          name: 'Background Text',
          isLocked: true,
          isCollapsed: true,
        },
        '581825a0-be14-4515-b819-4bfacec3bf38': {
          name: 'Image',
          isLocked: false,
          isCollapsed: true,
        },
      },
    },
  ],
};

export default fashionInspirationTemplate;
